export const homePopularHotelsFilter = [
  {
    id: "1",
    label: "New York",
  },
  {
    id: "1",
    label: "London",
  },
  {
    id: "1",
    label: "Parish",
  },
  {
    id: "1",
    label: "Istanbul",
  },
];

export const whyChooseUs = [
  {
    id: "1",
    image: "/1.svg",
    title: "Best Price Guarantee",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "2",

    image: "/2.svg",
    title: "Easy & Quick Booking",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "3",

    image: "/3.svg",
    title: "Customer Care 24/7",
    subTitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];

export const papularHotels = [
  {
    id: "1",
    image: "/2.png",
    title: "The Montcalm At Brewery London City",
    subTitle: "Westminster Borough, London",
    rating: "4.8",
    middleText: "Exceptional",
    reviews: "3,014",
    amount: "US$1,200",
    label: "BreakFast Included",
    labelColor: "#051036",
  },
  {
    id: "2",
    image: "/hotel-image-2.png",
    title: "The Montcalm At Brewery London City",
    subTitle: "Westminster Borough, London",
    rating: "4.8",
    middleText: "Exceptional",
    reviews: "3,014",
    amount: "US$1,200",
  },

  {
    id: "3",
    image: "/3.png",
    title: "The Montcalm At Brewery London City",
    subTitle: "Westminster Borough, London",
    rating: "4.8",
    middleText: "Exceptional",
    reviews: "3,014",
    amount: "US$1,200",
    label: "Best Seller",
    labelColor: "#3554D1",
  },
  {
    id: "4",
    image: "/hotel-image-3.png",
    title: "The Montcalm At Brewery London City",
    subTitle: "Westminster Borough, London",
    rating: "4.8",
    middleText: "Exceptional",
    reviews: "3,014",
    amount: "US$1,200",
    label: "Best Seller",
    labelColor: "#3554D1",
  },
  {
    id: "5",
    image: "/hotel-image-4.png",
    title: "The Montcalm At Brewery London City",
    subTitle: "Westminster Borough, London",
    rating: "4.8",
    middleText: "Exceptional",
    reviews: "3,014",
    amount: "US$1,200",
    label: "-25% Today",
    labelColor: "#923E01",
  },
  {
    id: "6",
    image: "/hotel-image-4.png",
    title: "The Montcalm At Brewery London City",
    subTitle: "Westminster Borough, London",
    rating: "4.8",
    middleText: "Exceptional",
    reviews: "3,014",
    amount: "US$1,200",
    label: "Top Rated",
    labelColor: "#F8D448",
  },
  {
    id: "7",
    image: "/hotel-image-4.png",
    title: "The Montcalm At Brewery London City",
    subTitle: "Westminster Borough, London",
    rating: "4.8",
    middleText: "Exceptional",
    reviews: "3,014",
    amount: "US$1,200",
    label: "Best Seller",
    labelColor: "#3554D1",
  },
  {
    id: "8",
    image: "/hotel-image-2.png",
    title: "The Montcalm At Brewery London City",
    subTitle: "Westminster Borough, London",
    rating: "4.8",
    middleText: "Exceptional",
    reviews: "3,014",
    amount: "US$1,200",
    label: "Top Rated",
    labelColor: "#F8D448",
  },
];
